// Auto-generated by scripts/download-sg-images.ts
// Do not edit manually — re-run the script to update.

export const sgLocalArtistImages: Record<string, string> = {
  "cheer-accident": "/images/sg/artists/cheer-accident.jpg",
  "colossamite": "/images/sg/artists/colossamite.jpg",
  "dazzling-killmen": "/images/sg/artists/dazzling-killmen.jpg",
  "lake-of-dracula": "/images/sg/artists/lake-of-dracula.jpg",
  "melt-banana": "/images/sg/artists/melt-banana.jpg",
  "mount-shasta": "/images/sg/artists/mount-shasta.jpg",
  "quintron": "/images/sg/artists/quintron.jpg",
  "ruins": "/images/sg/artists/ruins.jpg",
  "us-maple": "/images/sg/artists/us-maple.jpg",
};

export const sgLocalReleaseImages: Record<number, string> = {
  4: "/images/sg/albums/release-4.jpg",
  5: "/images/sg/albums/release-5.jpg",
  7: "/images/sg/albums/release-7.jpg",
  8: "/images/sg/albums/release-8.jpg",
  9: "/images/sg/albums/release-9.jpg",
  10: "/images/sg/albums/release-10.jpg",
  12: "/images/sg/albums/release-12.jpg",
  13: "/images/sg/albums/release-13.jpg",
  14: "/images/sg/albums/release-14.jpg",
  15: "/images/sg/albums/release-15.jpg",
  16: "/images/sg/albums/release-16.jpg",
  20: "/images/sg/albums/release-20.jpg",
  21: "/images/sg/albums/release-21.jpg",
  22: "/images/sg/albums/release-22.jpg",
  23: "/images/sg/albums/release-23.jpg",
  24: "/images/sg/albums/release-24.jpg",
  25: "/images/sg/albums/release-25.jpg",
  26: "/images/sg/albums/release-26.jpg",
  27: "/images/sg/albums/release-27.jpg",
  28: "/images/sg/albums/release-28.jpg",
  31: "/images/sg/albums/release-31.jpg",
  32: "/images/sg/albums/release-32.jpg",
  33: "/images/sg/albums/release-33.jpg",
  34: "/images/sg/albums/release-34.jpg",
  35: "/images/sg/albums/release-35.jpg",
  36: "/images/sg/albums/release-36.jpg",
  37: "/images/sg/albums/release-37.jpg",
  38: "/images/sg/albums/release-38.jpg",
  39: "/images/sg/albums/release-39.jpg",
  40: "/images/sg/albums/release-40.jpg",
  41: "/images/sg/albums/release-41.jpg",
  42: "/images/sg/albums/release-42.jpg",
  43: "/images/sg/albums/release-43.jpg",
  44: "/images/sg/albums/release-44.jpg",
  45: "/images/sg/albums/release-45.jpg",
};

export function getSgLocalArtistImage(id: string): string | undefined {
  return sgLocalArtistImages[id];
}

export function getSgLocalReleaseImage(catalogNumber: number): string | undefined {
  return sgLocalReleaseImages[catalogNumber];
}
