export interface TriviaQuestion {
  id: number
  question: string
  options: string[]
  correctAnswer: number
  explanation: string
  category: "history" | "records" | "players" | "teams" | "rules"
}

export const triviaQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "Who holds the record for most career home runs?",
    options: ["Babe Ruth", "Hank Aaron", "Barry Bonds", "Willie Mays"],
    correctAnswer: 2,
    explanation: "Barry Bonds hit 762 career home runs, surpassing Hank Aaron's 755 in 2007.",
    category: "records",
  },
  {
    id: 2,
    question: "Which team won the first World Series in 1903?",
    options: ["New York Yankees", "Boston Americans", "Chicago Cubs", "Pittsburgh Pirates"],
    correctAnswer: 1,
    explanation: "The Boston Americans (later Red Sox) defeated the Pittsburgh Pirates 5 games to 3.",
    category: "history",
  },
  {
    id: 3,
    question: "What is the minimum distance for a home run in MLB?",
    options: ["300 feet", "325 feet", "350 feet", "375 feet"],
    correctAnswer: 1,
    explanation: "MLB rules require a minimum distance of 325 feet down the foul lines and 400 feet to center field.",
    category: "rules",
  },
  {
    id: 4,
    question: "Who threw the only perfect game in World Series history?",
    options: ["Sandy Koufax", "Don Larsen", "Nolan Ryan", "Randy Johnson"],
    correctAnswer: 1,
    explanation:
      "Don Larsen pitched a perfect game for the Yankees against the Dodgers in Game 5 of the 1956 World Series.",
    category: "history",
  },
  {
    id: 5,
    question: "Which player has the most career stolen bases?",
    options: ["Ty Cobb", "Lou Brock", "Rickey Henderson", "Tim Raines"],
    correctAnswer: 2,
    explanation: "Rickey Henderson stole 1,406 bases during his career, far surpassing Lou Brock's 938.",
    category: "records",
  },
  {
    id: 6,
    question: "What year did Jackie Robinson break the color barrier?",
    options: ["1945", "1947", "1949", "1951"],
    correctAnswer: 1,
    explanation: "Jackie Robinson debuted for the Brooklyn Dodgers on April 15, 1947.",
    category: "history",
  },
  {
    id: 7,
    question: "Which pitcher holds the record for most career strikeouts?",
    options: ["Randy Johnson", "Roger Clemens", "Nolan Ryan", "Steve Carlton"],
    correctAnswer: 2,
    explanation: "Nolan Ryan struck out 5,714 batters during his 27-year career.",
    category: "records",
  },
  {
    id: 8,
    question: "How many stitches are on a regulation MLB baseball?",
    options: ["88", "108", "128", "148"],
    correctAnswer: 1,
    explanation: "Every MLB baseball has exactly 108 double stitches (216 individual stitches).",
    category: "rules",
  },
  {
    id: 9,
    question: "Which team has won the most World Series titles?",
    options: ["St. Louis Cardinals", "Boston Red Sox", "New York Yankees", "San Francisco Giants"],
    correctAnswer: 2,
    explanation: "The New York Yankees have won 27 World Series championships.",
    category: "teams",
  },
  {
    id: 10,
    question: "Who hit the 'Shot Heard Round the World' in 1951?",
    options: ["Willie Mays", "Bobby Thomson", "Jackie Robinson", "Duke Snider"],
    correctAnswer: 1,
    explanation: "Bobby Thomson's walk-off home run won the pennant for the Giants against the Dodgers.",
    category: "history",
  },
  {
    id: 11,
    question: "What is the highest single-season batting average since 1900?",
    options: [".406", ".424", ".426", ".440"],
    correctAnswer: 2,
    explanation: "Rogers Hornsby hit .424 for the Cardinals in 1924, the highest since 1900.",
    category: "records",
  },
  {
    id: 12,
    question: "Which stadium is known as 'The House That Ruth Built'?",
    options: ["Fenway Park", "Wrigley Field", "Old Yankee Stadium", "Polo Grounds"],
    correctAnswer: 2,
    explanation: "The original Yankee Stadium (1923-2008) earned this nickname due to Babe Ruth's star power.",
    category: "teams",
  },
  {
    id: 13,
    question: "Who was the first player to earn $1 million per year?",
    options: ["Reggie Jackson", "Pete Rose", "Nolan Ryan", "Mike Schmidt"],
    correctAnswer: 2,
    explanation: "Nolan Ryan became MLB's first $1 million per year player when he signed with the Astros in 1980.",
    category: "players",
  },
  {
    id: 14,
    question: "What is the longest game in MLB history by innings?",
    options: ["22 innings", "25 innings", "26 innings", "33 innings"],
    correctAnswer: 2,
    explanation: "The Dodgers and Red Sox played 26 innings on October 27, 2018 (World Series).",
    category: "history",
  },
  {
    id: 15,
    question: "Which player has the most Gold Glove awards?",
    options: ["Ozzie Smith", "Roberto Clemente", "Greg Maddux", "Brooks Robinson"],
    correctAnswer: 2,
    explanation: "Greg Maddux won 18 Gold Glove awards during his career as a pitcher.",
    category: "players",
  },
  {
    id: 16,
    question: "What is a 'cycle' in baseball?",
    options: [
      "Pitching 9 innings",
      "Hitting single, double, triple, and HR in one game",
      "Turning a triple play",
      "Stealing all four bases",
    ],
    correctAnswer: 1,
    explanation: "Hitting for the cycle means getting a single, double, triple, and home run in the same game.",
    category: "rules",
  },
  {
    id: 17,
    question: "Who was the youngest player to reach 3,000 hits?",
    options: ["Ty Cobb", "Pete Rose", "Hank Aaron", "Robin Yount"],
    correctAnswer: 0,
    explanation: "Ty Cobb reached 3,000 hits at age 34 years and 244 days in 1921.",
    category: "records",
  },
  {
    id: 18,
    question: "Which franchise moved from Milwaukee to Atlanta?",
    options: ["Brewers", "Braves", "Twins", "Orioles"],
    correctAnswer: 1,
    explanation: "The Braves played in Milwaukee from 1953-1965 before moving to Atlanta in 1966.",
    category: "teams",
  },
  {
    id: 19,
    question: "What is the 'Mendoza Line' named after?",
    options: ["A famous umpire", "A light-hitting shortstop", "A stadium", "A rule change"],
    correctAnswer: 1,
    explanation: "Named after Mario Mendoza, it represents a .200 batting average—the threshold of poor hitting.",
    category: "players",
  },
  {
    id: 20,
    question: "How many players are on the field for the defensive team?",
    options: ["8", "9", "10", "11"],
    correctAnswer: 1,
    explanation:
      "Nine players: pitcher, catcher, first baseman, second baseman, shortstop, third baseman, and three outfielders.",
    category: "rules",
  },
  {
    id: 21,
    question: "Who holds the record for most consecutive games played?",
    options: ["Lou Gehrig", "Cal Ripken Jr.", "Pete Rose", "Steve Garvey"],
    correctAnswer: 1,
    explanation: "Cal Ripken Jr. played 2,632 consecutive games from 1982 to 1998.",
    category: "records",
  },
  {
    id: 22,
    question: "What year was the designated hitter rule introduced in the AL?",
    options: ["1969", "1973", "1977", "1981"],
    correctAnswer: 1,
    explanation: "The American League adopted the DH rule in 1973. The NL followed in 2022.",
    category: "rules",
  },
  {
    id: 23,
    question: "Which brothers both won MVP awards?",
    options: ["Alou brothers", "DiMaggio brothers", "Aaron brothers", "Molina brothers"],
    correctAnswer: 1,
    explanation:
      "Joe DiMaggio won 3 MVPs and his brother Dom was a 7-time All-Star (though Dom never won MVP, Joe did).",
    category: "players",
  },
  {
    id: 24,
    question: "What is the oldest MLB stadium still in use?",
    options: ["Wrigley Field", "Fenway Park", "Dodger Stadium", "Oakland Coliseum"],
    correctAnswer: 1,
    explanation: "Fenway Park opened on April 20, 1912, making it the oldest active MLB stadium.",
    category: "teams",
  },
  {
    id: 25,
    question: "Who pitched the most no-hitters in MLB history?",
    options: ["Sandy Koufax", "Bob Feller", "Nolan Ryan", "Randy Johnson"],
    correctAnswer: 2,
    explanation: "Nolan Ryan threw 7 career no-hitters, 3 more than any other pitcher.",
    category: "records",
  },
  {
    id: 26,
    question: "What is a 'walk-off' hit?",
    options: [
      "A hit that ends an inning",
      "A game-winning hit by the home team in their final at-bat",
      "A hit that clears the bases",
      "A hit during a pitching change",
    ],
    correctAnswer: 1,
    explanation: "A walk-off hit ends the game immediately when the home team takes the lead in their last at-bat.",
    category: "rules",
  },
  {
    id: 27,
    question: "Which player won the Triple Crown most recently before 2012?",
    options: ["Ted Williams", "Mickey Mantle", "Frank Robinson", "Carl Yastrzemski"],
    correctAnswer: 3,
    explanation: "Carl Yastrzemski won the Triple Crown in 1967. Miguel Cabrera ended the 45-year drought in 2012.",
    category: "history",
  },
  {
    id: 28,
    question: "What is the 'Green Monster'?",
    options: ["Oakland's mascot", "Fenway Park's left field wall", "A type of curveball", "Chicago's ivy walls"],
    correctAnswer: 1,
    explanation: "The Green Monster is Fenway Park's famous 37-foot left field wall, painted green since 1947.",
    category: "teams",
  },
  {
    id: 29,
    question: "Who was the first African American manager in MLB?",
    options: ["Jackie Robinson", "Frank Robinson", "Dusty Baker", "Cito Gaston"],
    correctAnswer: 1,
    explanation: "Frank Robinson became MLB's first Black manager when he was hired by the Indians in 1975.",
    category: "history",
  },
  {
    id: 30,
    question: "What is the most runs scored in a single MLB game by one team?",
    options: ["27", "30", "33", "36"],
    correctAnswer: 1,
    explanation: "The Texas Rangers scored 30 runs against the Baltimore Orioles on August 22, 2007.",
    category: "records",
  },
  {
    id: 31,
    question: "Who was the first player to hit 60 home runs in a season?",
    options: ["Babe Ruth", "Roger Maris", "Mark McGwire", "Sammy Sosa"],
    correctAnswer: 0,
    explanation: "Babe Ruth hit 60 home runs in 1927, a record that stood for 34 years.",
    category: "records",
  },
  {
    id: 32,
    question: "What team did Babe Ruth play for before the Yankees?",
    options: ["Philadelphia Athletics", "Boston Red Sox", "Chicago White Sox", "Detroit Tigers"],
    correctAnswer: 1,
    explanation:
      "Babe Ruth started his career with the Boston Red Sox as a pitcher before being sold to the Yankees in 1920.",
    category: "history",
  },
  {
    id: 33,
    question: "Who holds the record for most hits in a single season?",
    options: ["Ty Cobb", "George Sisler", "Ichiro Suzuki", "Pete Rose"],
    correctAnswer: 2,
    explanation: "Ichiro Suzuki had 262 hits in 2004, breaking George Sisler's 84-year-old record of 257.",
    category: "records",
  },
  {
    id: 34,
    question: "Which pitcher won the most Cy Young Awards?",
    options: ["Randy Johnson", "Roger Clemens", "Greg Maddux", "Steve Carlton"],
    correctAnswer: 1,
    explanation: "Roger Clemens won 7 Cy Young Awards during his career.",
    category: "records",
  },
  {
    id: 35,
    question: "What does 'WHIP' stand for in baseball statistics?",
    options: [
      "Wins Held In Proportion",
      "Walks and Hits per Innings Pitched",
      "Winning Hits In Play",
      "Weighted Hitting Impact Percentage",
    ],
    correctAnswer: 1,
    explanation: "WHIP measures the number of walks and hits a pitcher allows per inning pitched.",
    category: "rules",
  },
  {
    id: 36,
    question: "Which team broke the 'Curse of the Bambino' in 2004?",
    options: ["Chicago Cubs", "Boston Red Sox", "Cleveland Indians", "Chicago White Sox"],
    correctAnswer: 1,
    explanation:
      "The Red Sox won the 2004 World Series, ending an 86-year championship drought since trading Babe Ruth.",
    category: "history",
  },
  {
    id: 37,
    question: "Who was known as 'The Say Hey Kid'?",
    options: ["Hank Aaron", "Willie Mays", "Mickey Mantle", "Roberto Clemente"],
    correctAnswer: 1,
    explanation: "Willie Mays earned this nickname for his enthusiastic greeting of 'Say hey!' to teammates and fans.",
    category: "players",
  },
  {
    id: 38,
    question: "What is the 'infield fly rule' designed to prevent?",
    options: ["Stolen bases", "Double plays on easy fly balls", "Hit batters", "Balks"],
    correctAnswer: 1,
    explanation:
      "The rule prevents infielders from intentionally dropping pop-ups to turn easy double or triple plays.",
    category: "rules",
  },
  {
    id: 39,
    question: "Which stadium has the deepest center field in MLB?",
    options: ["Coors Field", "Comerica Park", "Minute Maid Park", "Oracle Park"],
    correctAnswer: 1,
    explanation: "Comerica Park's center field is 420 feet from home plate.",
    category: "teams",
  },
  {
    id: 40,
    question: "Who threw the fastest pitch ever officially recorded?",
    options: ["Nolan Ryan", "Aroldis Chapman", "Joel Zumaya", "Justin Verlander"],
    correctAnswer: 1,
    explanation: "Aroldis Chapman threw a 105.8 mph fastball in 2010, the fastest ever recorded by Statcast.",
    category: "records",
  },
  {
    id: 41,
    question: "What year did the Seattle Mariners win 116 games?",
    options: ["1998", "2001", "2004", "2007"],
    correctAnswer: 1,
    explanation: "The 2001 Mariners won 116 games, tying the 1906 Cubs for most wins in a season.",
    category: "history",
  },
  {
    id: 42,
    question: "Who has the most career RBIs in MLB history?",
    options: ["Babe Ruth", "Hank Aaron", "Lou Gehrig", "Barry Bonds"],
    correctAnswer: 1,
    explanation: "Hank Aaron drove in 2,297 runs during his 23-year career.",
    category: "records",
  },
  {
    id: 43,
    question: "What is a 'balk' in baseball?",
    options: ["A wild pitch", "An illegal pitching motion", "A missed swing", "A foul ball"],
    correctAnswer: 1,
    explanation: "A balk is an illegal motion by the pitcher that deceives baserunners, advancing them one base.",
    category: "rules",
  },
  {
    id: 44,
    question: "Which team plays at Wrigley Field?",
    options: ["Chicago White Sox", "Chicago Cubs", "Milwaukee Brewers", "St. Louis Cardinals"],
    correctAnswer: 1,
    explanation: "The Chicago Cubs have called Wrigley Field home since 1916.",
    category: "teams",
  },
  {
    id: 45,
    question: "Who was the first player to be unanimously elected to the Hall of Fame?",
    options: ["Babe Ruth", "Ty Cobb", "Ken Griffey Jr.", "Mariano Rivera"],
    correctAnswer: 3,
    explanation: "Mariano Rivera received 100% of the vote in 2019, the first unanimous selection.",
    category: "history",
  },
  {
    id: 46,
    question: "What is the 'hot corner' in baseball?",
    options: ["Home plate", "Third base", "First base", "The dugout"],
    correctAnswer: 1,
    explanation: "Third base is called the hot corner due to the hard-hit balls and quick reaction time needed.",
    category: "rules",
  },
  {
    id: 47,
    question: "Who holds the record for most career walks?",
    options: ["Babe Ruth", "Ted Williams", "Barry Bonds", "Rickey Henderson"],
    correctAnswer: 2,
    explanation: "Barry Bonds walked 2,558 times in his career, including an MLB-record 232 in 2004.",
    category: "records",
  },
  {
    id: 48,
    question: "Which expansion team won a World Series in just their fifth season?",
    options: ["Colorado Rockies", "Arizona Diamondbacks", "Tampa Bay Rays", "Miami Marlins"],
    correctAnswer: 1,
    explanation: "The Arizona Diamondbacks won the 2001 World Series, just four years after their founding.",
    category: "teams",
  },
  {
    id: 49,
    question: "What is 'batting around' in baseball?",
    options: [
      "Switch hitting",
      "When all 9 batters come to the plate in one inning",
      "A batting practice drill",
      "A pinch-hit situation",
    ],
    correctAnswer: 1,
    explanation: "Batting around occurs when a team sends all nine batters to the plate in a single inning.",
    category: "rules",
  },
  {
    id: 50,
    question: "Who was MLB's first $30 million per year player?",
    options: ["Alex Rodriguez", "Derek Jeter", "Mike Trout", "Manny Ramirez"],
    correctAnswer: 0,
    explanation: "Alex Rodriguez signed a 10-year, $252 million contract with Texas in 2000.",
    category: "history",
  },
  {
    id: 51,
    question: "What is a 'can of corn' in baseball slang?",
    options: ["A home run", "An easy fly ball", "A strikeout", "A ground ball"],
    correctAnswer: 1,
    explanation: "An easy fly ball that falls softly into a fielder's glove, like cans being caught from a shelf.",
    category: "rules",
  },
  {
    id: 52,
    question: "Which player hit the longest verified home run?",
    options: ["Mickey Mantle", "Babe Ruth", "Mark McGwire", "Giancarlo Stanton"],
    correctAnswer: 0,
    explanation: "Mickey Mantle's 1953 shot at Griffith Stadium was measured at 565 feet.",
    category: "records",
  },
  {
    id: 53,
    question: "What team did Derek Jeter play his entire career for?",
    options: ["Boston Red Sox", "New York Mets", "New York Yankees", "Baltimore Orioles"],
    correctAnswer: 2,
    explanation: "Derek Jeter spent all 20 seasons (1995-2014) with the New York Yankees.",
    category: "players",
  },
  {
    id: 54,
    question: "Who was nicknamed 'The Big Unit'?",
    options: ["Frank Thomas", "Randy Johnson", "David Ortiz", "Mark McGwire"],
    correctAnswer: 1,
    explanation: "At 6'10\", Randy Johnson earned this nickname for his imposing height on the mound.",
    category: "players",
  },
  {
    id: 55,
    question: "What year did MLB expand to 30 teams?",
    options: ["1993", "1998", "2000", "2005"],
    correctAnswer: 1,
    explanation: "The Arizona Diamondbacks and Tampa Bay Devil Rays joined MLB in 1998.",
    category: "history",
  },
  {
    id: 56,
    question: "Which catcher has the most career home runs?",
    options: ["Johnny Bench", "Mike Piazza", "Carlton Fisk", "Ivan Rodriguez"],
    correctAnswer: 1,
    explanation: "Mike Piazza hit 427 career home runs, 396 of them as a catcher.",
    category: "records",
  },
  {
    id: 57,
    question: "What is a 'brushback pitch'?",
    options: ["A changeup", "A pitch thrown close to move the batter back", "A curveball", "A pitch to first base"],
    correctAnswer: 1,
    explanation: "A brushback is an inside pitch intended to make the batter step away from the plate.",
    category: "rules",
  },
  {
    id: 58,
    question: "Which team has the longest World Series drought currently?",
    options: ["Cleveland Guardians", "Seattle Mariners", "Milwaukee Brewers", "San Diego Padres"],
    correctAnswer: 1,
    explanation: "The Seattle Mariners have never won a World Series and have never even appeared in one.",
    category: "teams",
  },
  {
    id: 59,
    question: "Who was known as 'Mr. October'?",
    options: ["Mickey Mantle", "Reggie Jackson", "David Ortiz", "Derek Jeter"],
    correctAnswer: 1,
    explanation:
      "Reggie Jackson earned this nickname for his clutch postseason performances, especially in the World Series.",
    category: "players",
  },
  {
    id: 60,
    question: "What is the 'suicide squeeze' play?",
    options: [
      "A double steal",
      "A bunt with runner on third breaking for home on the pitch",
      "A hidden ball trick",
      "A pickoff play",
    ],
    correctAnswer: 1,
    explanation: "The runner breaks for home as the pitch is delivered, relying on the batter to make contact.",
    category: "rules",
  },
  {
    id: 61,
    question: "Who holds the record for most career games played?",
    options: ["Cal Ripken Jr.", "Pete Rose", "Hank Aaron", "Carl Yastrzemski"],
    correctAnswer: 1,
    explanation: "Pete Rose played in 3,562 career games over 24 seasons.",
    category: "records",
  },
  {
    id: 62,
    question: "What year did the Colorado Rockies and Florida Marlins join MLB?",
    options: ["1991", "1993", "1995", "1998"],
    correctAnswer: 1,
    explanation: "Both teams began play in 1993 as expansion franchises.",
    category: "history",
  },
  {
    id: 63,
    question: "Who was the first Japanese-born player in MLB?",
    options: ["Ichiro Suzuki", "Hideo Nomo", "Hideki Matsui", "Masanori Murakami"],
    correctAnswer: 3,
    explanation: "Masanori Murakami pitched for the San Francisco Giants in 1964-65.",
    category: "history",
  },
  {
    id: 64,
    question: "What is a 'twin killing' in baseball?",
    options: ["Hitting two home runs", "A double play", "Two strikeouts in a row", "Back-to-back errors"],
    correctAnswer: 1,
    explanation: "A twin killing is slang for a double play, getting two outs on one batted ball.",
    category: "rules",
  },
  {
    id: 65,
    question: "Which ballpark is at the highest elevation?",
    options: ["Chase Field", "Coors Field", "Oracle Park", "Dodger Stadium"],
    correctAnswer: 1,
    explanation: "Coors Field in Denver sits at 5,280 feet above sea level, affecting ball flight significantly.",
    category: "teams",
  },
  {
    id: 66,
    question: "Who has the most career doubles in MLB history?",
    options: ["Tris Speaker", "Pete Rose", "Stan Musial", "Craig Biggio"],
    correctAnswer: 0,
    explanation: "Tris Speaker hit 792 career doubles, 46 more than second-place Pete Rose.",
    category: "records",
  },
  {
    id: 67,
    question: "What is the 'neighborhood play'?",
    options: [
      "A home run to the stands",
      "A second baseman not touching the bag on a double play",
      "A stolen base",
      "A walk-off hit",
    ],
    correctAnswer: 1,
    explanation:
      "The neighborhood play allowed middle infielders to be near but not touching second base on double plays.",
    category: "rules",
  },
  {
    id: 68,
    question: "Who hit the first home run at new Yankee Stadium?",
    options: ["Derek Jeter", "Johnny Damon", "Jorge Posada", "Robinson Cano"],
    correctAnswer: 1,
    explanation: "Johnny Damon hit the first homer at the new Yankee Stadium on April 16, 2009.",
    category: "history",
  },
  {
    id: 69,
    question: "Which pitcher has the lowest career ERA (minimum 1500 innings)?",
    options: ["Walter Johnson", "Christy Mathewson", "Ed Walsh", "Mariano Rivera"],
    correctAnswer: 2,
    explanation: "Ed Walsh had a career ERA of 1.82 over 2,964 innings pitched from 1904-1917.",
    category: "records",
  },
  {
    id: 70,
    question: "What is 'OPS' a combination of?",
    options: ["Outs Per Season", "On-base Plus Slugging", "Offensive Player Score", "Overall Pitching Stats"],
    correctAnswer: 1,
    explanation: "OPS adds a player's on-base percentage and slugging percentage together.",
    category: "rules",
  },
  {
    id: 71,
    question: "Which team won back-to-back World Series in 1992 and 1993?",
    options: ["Atlanta Braves", "Toronto Blue Jays", "Oakland Athletics", "Minnesota Twins"],
    correctAnswer: 1,
    explanation: "The Toronto Blue Jays won consecutive championships, the only Canadian team to win the World Series.",
    category: "teams",
  },
  {
    id: 72,
    question: "Who was the first player to hit 500 career home runs?",
    options: ["Babe Ruth", "Jimmie Foxx", "Mel Ott", "Ted Williams"],
    correctAnswer: 0,
    explanation: "Babe Ruth reached 500 home runs on August 11, 1929.",
    category: "history",
  },
  {
    id: 73,
    question: "What is a 'Golden Sombrero' in baseball?",
    options: [
      "Winning the batting title",
      "Striking out four times in one game",
      "Hitting for the cycle",
      "A defensive gem",
    ],
    correctAnswer: 1,
    explanation: "A Golden Sombrero refers to a batter striking out four times in a single game.",
    category: "rules",
  },
  {
    id: 74,
    question: "Who holds the record for most saves in a career?",
    options: ["Trevor Hoffman", "Mariano Rivera", "Lee Smith", "Dennis Eckersley"],
    correctAnswer: 1,
    explanation: "Mariano Rivera recorded 652 career saves over his 19-year career with the Yankees.",
    category: "records",
  },
  {
    id: 75,
    question: "What nickname was given to the 1927 Yankees lineup?",
    options: ["The Big Red Machine", "Murderers' Row", "The Bronx Bombers", "The Bash Brothers"],
    correctAnswer: 1,
    explanation: "Murderers' Row featured Babe Ruth, Lou Gehrig, and other power hitters on the legendary 1927 team.",
    category: "history",
  },
  {
    id: 76,
    question: "Which player won MVP awards in both leagues?",
    options: ["Barry Bonds", "Frank Robinson", "Alex Rodriguez", "All of the above"],
    correctAnswer: 1,
    explanation: "Frank Robinson won MVP with Cincinnati (1961) and Baltimore (1966), the first to do so.",
    category: "players",
  },
  {
    id: 77,
    question: "What is the 'Mendoza Line'?",
    options: [".300 batting average", ".250 batting average", ".200 batting average", ".150 batting average"],
    correctAnswer: 2,
    explanation: "The Mendoza Line represents a .200 batting average, considered the threshold of acceptable hitting.",
    category: "rules",
  },
  {
    id: 78,
    question: "Which team moved from Brooklyn to Los Angeles?",
    options: ["Giants", "Dodgers", "Athletics", "Senators"],
    correctAnswer: 1,
    explanation: "The Brooklyn Dodgers moved to Los Angeles after the 1957 season.",
    category: "teams",
  },
  {
    id: 79,
    question: "Who was the youngest player to reach 600 home runs?",
    options: ["Babe Ruth", "Hank Aaron", "Alex Rodriguez", "Barry Bonds"],
    correctAnswer: 2,
    explanation: "Alex Rodriguez reached 600 home runs at age 35 years, 8 days in 2010.",
    category: "records",
  },
  {
    id: 80,
    question: "What is a 'Baltimore chop'?",
    options: ["A type of pitch", "A high-bouncing ground ball", "A defensive shift", "A base-stealing technique"],
    correctAnswer: 1,
    explanation:
      "A Baltimore chop is a ground ball that bounces high off the plate or hard dirt, often resulting in a hit.",
    category: "rules",
  },
  {
    id: 81,
    question: "Who threw the last pitch of the 2016 World Series?",
    options: ["Aroldis Chapman", "Mike Montgomery", "Jon Lester", "Kyle Hendricks"],
    correctAnswer: 1,
    explanation: "Mike Montgomery got the final out as the Cubs won their first championship in 108 years.",
    category: "history",
  },
  {
    id: 82,
    question: "Which player has the most All-Star Game selections?",
    options: ["Hank Aaron", "Willie Mays", "Stan Musial", "Pete Rose"],
    correctAnswer: 0,
    explanation: "Hank Aaron was selected to 25 All-Star Games during his career.",
    category: "records",
  },
  {
    id: 83,
    question: "What does 'WAR' stand for in baseball analytics?",
    options: ["Wins Above Replacement", "Weighted Average Runs", "Walk And Run", "Win Advance Rating"],
    correctAnswer: 0,
    explanation: "WAR measures a player's total value compared to a replacement-level player.",
    category: "rules",
  },
  {
    id: 84,
    question: "Which team has retired the most jersey numbers?",
    options: ["Boston Red Sox", "New York Yankees", "St. Louis Cardinals", "Los Angeles Dodgers"],
    correctAnswer: 1,
    explanation: "The New York Yankees have retired 23 numbers, more than any other team.",
    category: "teams",
  },
  {
    id: 85,
    question: "Who was the last Triple Crown winner before Miguel Cabrera?",
    options: ["Ted Williams", "Mickey Mantle", "Frank Robinson", "Carl Yastrzemski"],
    correctAnswer: 3,
    explanation: "Carl Yastrzemski won the Triple Crown in 1967, 45 years before Cabrera's 2012 achievement.",
    category: "history",
  },
  {
    id: 86,
    question: "What is an 'immaculate inning'?",
    options: ["Three strikeouts on 9 pitches", "A perfect game", "No balls thrown in an inning", "Three ground outs"],
    correctAnswer: 0,
    explanation: "An immaculate inning is when a pitcher strikes out three batters on exactly nine pitches.",
    category: "rules",
  },
  {
    id: 87,
    question: "Who hit the most home runs in their final season?",
    options: ["Babe Ruth", "Ted Williams", "Dave Kingman", "Mark McGwire"],
    correctAnswer: 1,
    explanation: "Ted Williams hit 29 home runs in 1960, his final season, including a homer in his last at-bat.",
    category: "records",
  },
  {
    id: 88,
    question: "Which team has never had a no-hitter thrown by their pitchers?",
    options: ["San Diego Padres", "New York Mets", "Colorado Rockies", "Tampa Bay Rays"],
    correctAnswer: 0,
    explanation: "The San Diego Padres are the only franchise to have never had a pitcher throw a no-hitter.",
    category: "teams",
  },
  {
    id: 89,
    question: "Who was nicknamed 'The Splendid Splinter'?",
    options: ["Joe DiMaggio", "Ted Williams", "Stan Musial", "Mickey Mantle"],
    correctAnswer: 1,
    explanation: "Ted Williams earned this nickname due to his thin frame and exceptional hitting ability.",
    category: "players",
  },
  {
    id: 90,
    question: "What is the maximum number of players on an active MLB roster during the regular season?",
    options: ["25", "26", "28", "40"],
    correctAnswer: 1,
    explanation: "MLB expanded the regular-season active roster from 25 to 26 players starting in 2020.",
    category: "rules",
  },
  {
    id: 91,
    question: "Which father-son duo both hit 200+ career home runs?",
    options: ["Bobby and Barry Bonds", "Ken Griffey Sr. and Jr.", "Cecil and Prince Fielder", "All of the above"],
    correctAnswer: 3,
    explanation: "All three father-son combinations achieved this milestone.",
    category: "players",
  },
  {
    id: 92,
    question: "What year did instant replay reviews begin in MLB?",
    options: ["2008", "2010", "2014", "2016"],
    correctAnswer: 2,
    explanation: "MLB expanded replay review to include most calls starting in 2014.",
    category: "history",
  },
  {
    id: 93,
    question: "Who holds the record for most strikeouts in a 9-inning game?",
    options: ["Nolan Ryan", "Roger Clemens", "Kerry Wood", "Max Scherzer"],
    correctAnswer: 2,
    explanation: "Kerry Wood and Roger Clemens both struck out 20 batters in a 9-inning game.",
    category: "records",
  },
  {
    id: 94,
    question: "What is a 'pickle' in baseball?",
    options: ["A difficult pitch", "A rundown between bases", "A defensive error", "A bad hop"],
    correctAnswer: 1,
    explanation: "A pickle is when a baserunner is caught between two bases and fielders try to tag them out.",
    category: "rules",
  },
  {
    id: 95,
    question: "Which stadium opened in 1912 and is still in use today?",
    options: ["Wrigley Field", "Fenway Park", "Yankee Stadium", "Dodger Stadium"],
    correctAnswer: 1,
    explanation: "Fenway Park opened on April 20, 1912, making it MLB's oldest active ballpark.",
    category: "teams",
  },
  {
    id: 96,
    question: "Who was the first MLB player to earn $1 million in a single season?",
    options: ["Hank Aaron", "Catfish Hunter", "Nolan Ryan", "Pete Rose"],
    correctAnswer: 2,
    explanation: "Nolan Ryan became the first $1 million per year player when he signed with the Astros in 1980.",
    category: "history",
  },
  {
    id: 97,
    question: "What is a 'Texas Leaguer'?",
    options: ["A home run", "A blooper hit", "A curveball", "A stolen base"],
    correctAnswer: 1,
    explanation: "A Texas Leaguer is a softly hit ball that drops between the infield and outfield for a hit.",
    category: "rules",
  },
  {
    id: 98,
    question: "Who holds the record for most grand slams in a career?",
    options: ["Lou Gehrig", "Manny Ramirez", "Alex Rodriguez", "Eddie Murray"],
    correctAnswer: 2,
    explanation: "Alex Rodriguez hit 25 career grand slams, surpassing Lou Gehrig's 23.",
    category: "records",
  },
  {
    id: 99,
    question: "Which team plays at Oracle Park?",
    options: ["Oakland Athletics", "San Francisco Giants", "San Diego Padres", "Los Angeles Angels"],
    correctAnswer: 1,
    explanation: "The San Francisco Giants have played at Oracle Park (formerly AT&T Park) since 2000.",
    category: "teams",
  },
  {
    id: 100,
    question: "Who was the first designated hitter to be inducted into the Hall of Fame?",
    options: ["Edgar Martinez", "David Ortiz", "Frank Thomas", "Harold Baines"],
    correctAnswer: 0,
    explanation: "Edgar Martinez was inducted in 2019, primarily recognized for his role as a DH with the Mariners.",
    category: "history",
  },
]

export function getDailyTriviaQuestions(date?: Date): TriviaQuestion[] {
  const now = date || new Date()
  // Create a seed based on the current date (changes daily at midnight)
  const dateSeed = now.getFullYear() * 10000 + (now.getMonth() + 1) * 100 + now.getDate()

  const seededRandom = (seed: number): number => {
    const x = Math.sin(seed) * 10000
    return x - Math.floor(x)
  }

  const totalQuestions = triviaQuestions.length
  const selectedIndices: number[] = []
  let seed = dateSeed

  // Select 5 unique random indices
  while (selectedIndices.length < 5) {
    seed = (seed * 16807) % 2147483647 // Linear congruential generator
    const randomValue = seededRandom(seed)
    const index = Math.floor(randomValue * totalQuestions)

    if (!selectedIndices.includes(index)) {
      selectedIndices.push(index)
    }
  }

  // Return 5 unique questions
  return selectedIndices.map((i) => triviaQuestions[i])
}

export function getTodayStorageKey(date?: Date): string {
  const now = date || new Date()
  return `trivia-${now.getFullYear()}-${now.getMonth() + 1}-${now.getDate()}`
}

export function getNextTriviaTime(): Date {
  const now = new Date()
  const tomorrow = new Date(now)
  tomorrow.setDate(tomorrow.getDate() + 1)
  tomorrow.setHours(0, 0, 0, 0)
  return tomorrow
}
